"""PDF Preview Service for Labor-Report.

Generates temporary preview PDFs before finalizing a report.
Preview PDFs do NOT replace the official report — they are saved
to a separate preview folder and do not update report.pdf_path.
"""

from pathlib import Path
from typing import Optional

from app.excel.template_filler import TemplateFiller
from app.models.config import AppConfig
from app.models.database import Report
from app.pdf.generator import PDFGenerator
from app.utils.logger import get_logger

logger = get_logger(__name__)


class PDFPreviewService:
    """Service for generating temporary preview PDFs.

    The preview PDF is generated by:
    1. Filling the Excel template with report data (via TemplateFiller).
    2. Converting the filled Excel to PDF (via PDFGenerator).
    3. Saving the PDF to the preview folder with a 'preview_' prefix.
    4. Updating the report's preview_pdf_path without modifying pdf_path.

    The preview can be overwritten by calling generate_preview again.
    """

    def __init__(
        self,
        template_filler: TemplateFiller,
        pdf_generator: PDFGenerator,
        config: AppConfig,
    ) -> None:
        """Initialize the PDF preview service.

        Args:
            template_filler: Service for filling Excel templates.
            pdf_generator: Service for converting Excel to PDF.
            config: Application configuration (for preview folder path).
        """
        self._template_filler = template_filler
        self._pdf_generator = pdf_generator
        self._config = config

    def generate_preview(self, report: Report) -> str:
        """Generate a preview PDF for the given report.

        Creates a temporary Excel file from the report data,
        converts it to PDF, saves it to the preview folder,
        and updates the report's preview_pdf_path.

        The report.pdf_path is NOT modified.

        Args:
            report: The report to generate a preview for.
                   The report's items are used to fill the template.

        Returns:
            Path to the generated preview PDF file.

        Raises:
            FileNotFoundError: If the Excel template is missing.
            PDFError: If PDF generation fails.
            ExcelFillError: If template filling fails.
        """
        # Step 1: Generate a temporary Excel file
        excel_path = self._generate_excel_path(report.date)
        filled_excel = self._template_filler.fill(report, output_path=excel_path)

        # Step 2: Generate preview PDF path
        preview_path = self._generate_preview_path(report.date)

        # Step 3: Convert Excel to PDF
        result_path = self._pdf_generator.convert_excel_to_pdf(
            filled_excel, output_path=preview_path,
        )

        # Step 4: Update the report's preview_pdf_path (NOT pdf_path)
        report.preview_pdf_path = result_path

        logger.info(
            "Preview PDF generated: date=%s, path=%s",
            report.date, result_path,
        )
        return result_path

    def cleanup_preview(self, date: str) -> None:
        """Delete the preview PDF and temporary Excel for a given date.

        Args:
            date: The report date in YYYY-MM-DD format.
        """
        preview_path = self._preview_folder() / f"preview_{date}.pdf"
        if preview_path.exists():
            preview_path.unlink()
            logger.info("Deleted preview PDF: %s", preview_path)

        excel_path = self._preview_folder() / f"{date}.xlsx"
        if excel_path.exists():
            excel_path.unlink()
            logger.info("Deleted preview Excel: %s", excel_path)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _generate_excel_path(self, date_str: str) -> str:
        """Generate the path for the temporary preview Excel file.

        Args:
            date_str: Date string in YYYY-MM-DD format.

        Returns:
            Full path to the temporary Excel file.
        """
        folder = self._preview_folder()
        return str(folder / f"{date_str}.xlsx")

    def _generate_preview_path(self, date_str: str) -> str:
        """Generate the path for the preview PDF file.

        Args:
            date_str: Date string in YYYY-MM-DD format.

        Returns:
            Full path to the preview PDF file.
        """
        folder = self._preview_folder()
        return str(folder / f"preview_{date_str}.pdf")

    def _preview_folder(self) -> Path:
        """Get the preview folder path, creating it if needed.

        Returns:
            Path to the preview folder.
        """
        folder = self._config.preview_folder_path
        folder.mkdir(parents=True, exist_ok=True)
        return folder
