"""Contractor v2 composer (period report, live path).

Converged onto the v3 cover+table system: cover via design.cover_rows
("contractor"), all-white/centered/wrap/padded, portrait A4, single
print-range + footer. Business data + approval states unchanged.
"""

from __future__ import annotations

from pathlib import Path

from odf.draw import Frame, Image
from odf.opendocument import OpenDocumentSpreadsheet
from odf.style import (
    Footer, MasterPage, PageLayout, PageLayoutProperties,
    ParagraphProperties, Style, TableCellProperties,
    TableColumnProperties, TableRowProperties, TextProperties,
)
from odf.table import Table, TableCell, TableColumn, TableRow
from odf.text import P, PageNumber

from app.libre import design as D

_ROOT = Path(__file__).parent.parent.parent.resolve()
LOGO_SRC = _ROOT / "assets" / "atlas_logo.png"
NCOLS = 6
WIDTHS = D.CONTRACTOR_V2_WIDTHS
HEADERS = ["Date", "Workers", "Zone", "Details", "Added By", "Role"]


def _ts(doc, name, size="10.5pt", bold=False, color=None, align="center"):
    st = Style(name=name, family="text")
    tp = TextProperties(fontfamily=D.FONTS, fontsize=size)
    if bold:
        tp.setAttribute("fontweight", "bold")
    if color:
        tp.setAttribute("color", color)
    st.addElement(tp)
    st.addElement(ParagraphProperties(textalign=align))
    doc.styles.addElement(st)
    return name


def _cs(doc, name, border=None, btop=None, bbot=None):
    st = Style(name=name, family="table-cell")
    p = TableCellProperties(verticalalign="middle", padding="2mm",
                            wrapoption="wrap")
    if border:
        p.setAttribute("border", border)
    if btop:
        p.setAttribute("bordertop", btop)
    if bbot:
        p.setAttribute("borderbottom", bbot)
    st.addElement(p)
    doc.automaticstyles.addElement(st)
    return name


def compose(ctx: dict, entries: list[tuple], out: str) -> str:
    doc = OpenDocumentSpreadsheet()
    lay = PageLayout(name="atlas_contractor_v2")
    lay.addElement(PageLayoutProperties(
        pagewidth="21cm", pageheight="29.7cm", printorientation="portrait",
        margintop="0.7cm", marginbottom="1cm", marginleft="1cm",
        marginright="1cm"))
    doc.automaticstyles.addElement(lay)
    mp = MasterPage(name="Default", pagelayoutname="atlas_contractor_v2")
    ft = Footer()
    fp = P()
    fp.addText("Generated by Atlas-Bot | Page ")
    fp.addElement(PageNumber())
    fstyle = _ts(doc, "cv2foot", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    fp.setAttribute("stylename", fstyle)
    ft.addElement(fp)
    mp.addElement(ft)
    doc.masterstyles.addElement(mp)
    tabst = Style(name="tab_cv2", family="table", masterpagename="Default")
    doc.automaticstyles.addElement(tabst)

    t_title = _ts(doc, "cv2title", size="17pt", bold=True)
    t_meta = _ts(doc, "cv2meta", size="10pt", bold=True)
    t_val = _ts(doc, "cv2val")
    t_hdr = _ts(doc, "cv2hdr", bold=True)
    t_foot = _ts(doc, "cv2footc", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    c_plain = _cs(doc, "cv2plain")
    c_cell = _cs(doc, "cv2cell", border=D.V2_HAIRLINE)
    c_hdr = _cs(doc, "cv2hdr", border=D.V2_HAIRLINE, bbot=D.V2_HDR_RULE)
    c_tot = _cs(doc, "cv2tot", border=D.V2_HAIRLINE, btop=D.V2_HDR_RULE)
    hr = Style(name="cv2headrow", family="table-row")
    hr.addElement(TableRowProperties(minrowheight="0.9cm"))
    doc.automaticstyles.addElement(hr)

    table = Table(name="Contractor", stylename="tab_cv2")
    for i, w in enumerate(WIDTHS):
        cs = Style(name="cv2col%d" % i, family="table-column")
        cs.addElement(TableColumnProperties(columnwidth=w))
        doc.automaticstyles.addElement(cs)
        col = TableColumn()
        col.setAttribute("stylename", "cv2col%d" % i)
        table.addElement(col)

    def mrow(text, tstyle, cstyle=c_plain):
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", cstyle)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", tstyle)
        p.addText(text)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)

    def drow(vals, cstyle, tstyle):
        r = TableRow()
        for v in vals:
            c = TableCell()
            c.setAttribute("stylename", cstyle)
            p = P()
            p.setAttribute("stylename", tstyle)
            p.addText(str(v))
            c.addElement(p)
            r.addElement(c)
        table.addElement(r)
        return r

    if LOGO_SRC.exists():
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", c_plain)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", fstyle)
        frame = Frame(name="Logo", width="3.2cm", height="1.1cm",
                      x="7.9cm", y="0.1cm", anchortype="paragraph")
        frame.addElement(Image(href="Pictures/atlas_logo.png", type="simple",
                               show="embed", actuate="onLoad"))
        p.addElement(frame)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)
    else:
        mrow("ATLAS-BOT", t_meta)
    mrow("Contractor Period Report", t_title)
    for _label, _val in D.cover_rows("contractor", ctx):
        mrow("%s: %s" % (_label, _val),
             t_val if _label == "Automated By" else t_meta)
    drow(list(HEADERS), c_hdr, t_hdr).setAttribute("stylename", "cv2headrow")
    total = 0
    for date, w, zone, det, by, role in entries:
        drow([date, w, zone, det, by, role], c_cell, t_val)
        total += w or 0
    drow(["Summary: %d entries" % len(entries), total, "", "", "", ""],
         c_tot, t_hdr)
    mrow("Generated by Atlas-Bot | %s" % ctx.get("period", ""), t_foot)

    nrows = len(table.getElementsByType(TableRow))
    table.setAttribute("printranges", "A1:F%d" % nrows)
    doc.spreadsheet.addElement(table)
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    doc.save(out)
    if LOGO_SRC.exists():
        from scripts.build_hr_templates import _embed_logo
        _embed_logo(out)
    return out


def build(contractor_name: str, start: str, end: str,
          entries: list[dict], company: str = "",
          output_path: str = "") -> str:
    """Legacy-shape entry dicts (date/workers/zone/details/added_by/role)."""
    ctx = {"company": company or "",
           "contractor": contractor_name or "",
           "period": "%s to %s" % (start, end),
           "automated-by": "Atlas-bot"}
    rows = [(e.get("date", ""), e.get("workers", 0) or 0,
             e.get("zone", ""), e.get("details", ""),
             e.get("added_by", ""), e.get("role", "")) for e in entries]
    return compose(ctx, rows, output_path)
