"""Daily v3 composer (live path). Same bytes as scripts/build_daily_v3.py.

Cover via design.cover_rows; OPAL fixture only when config lacks company key.
"""

from __future__ import annotations

import re
from pathlib import Path

from odf.draw import Frame, Image
from odf.opendocument import OpenDocumentSpreadsheet
from odf.style import (
    Footer, MasterPage, PageLayout, PageLayoutProperties,
    ParagraphProperties, Style, TableCellProperties,
    TableColumnProperties, TableRowProperties, TextProperties,
)
from odf.table import Table, TableCell, TableColumn, TableRow
from odf.text import P, PageNumber

from app.libre import design as D

_ROOT = Path(__file__).parent.parent.parent.resolve()
LOGO_SRC = _ROOT / "assets" / "atlas_logo.png"
NCOLS = 8
WIDTHS = D.DAILY_V2_WIDTHS
HEADERS = ["#", "Contractor", "Type", "Zone", "Workers", "Craftsmen",
           "Helpers", "Details"]
OPAL_COMPANY = "OPAL Construction Co."


def resolve_company(config=None) -> str:
    for src in (getattr(config, "company", None),
                (config.model_extra or {}).get("company") if config is not None and hasattr(config, "model_extra") else None,
                getattr(getattr(config, "auth", None), "company", None)):
        if src:
            return str(src).strip()
    try:
        m = re.search(r"^company:\s*[\"']?(.+?)[\"']?\s*$",
                      (_ROOT / "config" / "config.yaml").read_text(encoding="utf-8"), re.M)
        if m and m.group(1).strip():
            return m.group(1).strip()
    except OSError:
        pass
    return OPAL_COMPANY


def _ts(doc, name, size="10.5pt", bold=False, color=None, align="center"):
    st = Style(name=name, family="text")
    tp = TextProperties(fontfamily=D.FONTS, fontsize=size)
    if bold:
        tp.setAttribute("fontweight", "bold")
    if color:
        tp.setAttribute("color", color)
    st.addElement(tp)
    pp = ParagraphProperties(textalign=align)
    st.addElement(pp)
    doc.styles.addElement(st)
    return name


def _cs(doc, name, border=None, btop=None, bbot=None):
    st = Style(name=name, family="table-cell")
    p = TableCellProperties(verticalalign="middle", padding="2mm")
    if border:
        p.setAttribute("border", border)
    if btop:
        p.setAttribute("bordertop", btop)
    if bbot:
        p.setAttribute("borderbottom", bbot)
    st.addElement(p)
    doc.automaticstyles.addElement(st)
    return name


def compose(ctx: dict, rows: list[tuple], out: str) -> str:
    doc = OpenDocumentSpreadsheet()
    lay = PageLayout(name="atlas_v3")
    lay.addElement(PageLayoutProperties(
        pagewidth="21cm", pageheight="29.7cm", printorientation="portrait",
        margintop="0.7cm", marginbottom="1cm", marginleft="1cm",
        marginright="1cm"))
    doc.automaticstyles.addElement(lay)
    mp = MasterPage(name="Default", pagelayoutname="atlas_v3")
    ft = Footer()
    fp = P()
    fp.addText("Generated by Atlas-Bot | Page ")
    fp.addElement(PageNumber())
    fstyle = _ts(doc, "v3foot", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    fp.setAttribute("stylename", fstyle)
    ft.addElement(fp)
    mp.addElement(ft)
    doc.masterstyles.addElement(mp)
    tabst = Style(name="tab_v3", family="table", masterpagename="Default")
    doc.automaticstyles.addElement(tabst)

    t_title = _ts(doc, "v3title", size="17pt", bold=True)
    t_meta = _ts(doc, "v3meta", size="10pt", bold=True)
    t_val = _ts(doc, "v3val")
    t_hdr = _ts(doc, "v3hdr", bold=True)
    t_foot = _ts(doc, "v3footc", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    c_plain = _cs(doc, "v3plain")
    c_cell = _cs(doc, "v3cell", border=D.V2_HAIRLINE)
    c_hdr = _cs(doc, "v3hdr", border=D.V2_HAIRLINE, bbot=D.V2_HDR_RULE)
    c_tot = _cs(doc, "v3tot", border=D.V2_HAIRLINE, btop=D.V2_HDR_RULE)
    hr = Style(name="v3headrow", family="table-row")
    hr.addElement(TableRowProperties(minrowheight="0.9cm"))
    doc.automaticstyles.addElement(hr)

    table = Table(name="Daily", stylename="tab_v3")
    for i, w in enumerate(WIDTHS):
        cs = Style(name="v3col%d" % i, family="table-column")
        cs.addElement(TableColumnProperties(columnwidth=w))
        doc.automaticstyles.addElement(cs)
        col = TableColumn()
        col.setAttribute("stylename", "v3col%d" % i)
        table.addElement(col)

    def mrow(text, tstyle, cstyle=c_plain):
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", cstyle)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", tstyle)
        p.addText(text)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)

    def drow(vals, cstyle, tstyle):
        r = TableRow()
        for v in vals:
            c = TableCell()
            c.setAttribute("stylename", cstyle)
            p = P()
            p.setAttribute("stylename", tstyle)
            p.addText(str(v))
            c.addElement(p)
            r.addElement(c)
        table.addElement(r)
        return r

    if LOGO_SRC.exists():
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", c_plain)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", fstyle)
        frame = Frame(name="Logo", width="3.2cm", height="1.1cm",
                      x="7.9cm", y="0.1cm", anchortype="paragraph")
        frame.addElement(Image(href="Pictures/atlas_logo.png", type="simple",
                               show="embed", actuate="onLoad"))
        p.addElement(frame)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)
    else:
        mrow("ATLAS-BOT", t_meta)
    mrow("Daily Labor Report", t_title)
    for _label, _val in D.cover_rows("daily", ctx):
        mrow("%s: %s" % (_label, _val),
             t_val if _label == "Automated By" else t_meta)
    drow(list(HEADERS), c_hdr, t_hdr).setAttribute("stylename", "v3headrow")
    tw = tc = th = 0
    tc_none, th_none = True, True
    for n, (co, ty, zo, w, cr, he, de) in enumerate(rows, 1):
        drow([n, co, ty, zo, w, "" if cr is None else cr,
              "" if he is None else he, de], c_cell, t_val)
        tw += w or 0
        if cr is not None:
            tc += cr
            tc_none = False
        if he is not None:
            th += he
            th_none = False
    drow(["", "Total", "", "", tw, "" if tc_none else tc,
          "" if th_none else th, ""], c_tot, t_hdr)
    mrow("Generated by Atlas-Bot | %s" % ctx.get("date", ""), t_foot)

    nrows = len(table.getElementsByType(TableRow))
    table.setAttribute("printranges", "A1:H%d" % nrows)
    doc.spreadsheet.addElement(table)
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    doc.save(out)
    if LOGO_SRC.exists():
        from scripts.build_hr_templates import _embed_logo
        _embed_logo(out)
    return out


def build(report, config=None, output_path: str | None = None) -> str:
    from app.libre.filler import details_text

    if output_path is None:
        output_path = str(config.docs_folder_path / f"{report.date}.ods") \
            if config is not None else f"{report.date}.ods"
    ctx = {"company": resolve_company(config),
           "site": getattr(report, "site_id", "") or "",
           "date": report.date}
    rows = []
    for it in (report.items or []):
        w = it.workers or 0
        cr, he = it.craftsmen, it.helpers
        if cr is not None and he is None:
            he = w - cr
        rows.append((it.contractor or "", it.type or "", it.zone or "",
                     w, cr, he, details_text(it)))
    return compose(ctx, rows, output_path)
