"""HR v3 composers (Advance + Transport, EN-only).

Cover via design.cover_rows; table primitives mirror daily_v3 (all-white,
centered, wrap, padded, portrait A4, single print-range + footer).
Business data + approval states unchanged; doc layer only.
"""

from __future__ import annotations

from pathlib import Path

from odf.draw import Frame, Image
from odf.opendocument import OpenDocumentSpreadsheet
from odf.style import (
    Footer, MasterPage, PageLayout, PageLayoutProperties,
    ParagraphProperties, Style, TableCellProperties,
    TableColumnProperties, TableRowProperties, TextProperties,
)
from odf.table import Table, TableCell, TableColumn, TableRow
from odf.text import P, PageNumber

from app.libre import design as D

_ROOT = Path(__file__).parent.parent.parent.resolve()
LOGO_SRC = _ROOT / "assets" / "atlas_logo.png"
NCOLS = 4
WIDTHS = D.ADVANCE_WIDTHS  # 4 cols, portrait printable


def mask_chat(chat: str | None) -> str:
    s = str(chat or "").strip()
    if not s:
        return "-"
    return "***" + s[-4:] if len(s) > 4 else "***" + s  # ponytail: display-only


def _ts(doc, name, size="10.5pt", bold=False, color=None, align="center"):
    st = Style(name=name, family="text")
    tp = TextProperties(fontfamily=D.FONTS, fontsize=size)
    if bold:
        tp.setAttribute("fontweight", "bold")
    if color:
        tp.setAttribute("color", color)
    st.addElement(tp)
    st.addElement(ParagraphProperties(textalign=align))
    doc.styles.addElement(st)
    return name


def _cs(doc, name, border=None, btop=None, bbot=None):
    st = Style(name=name, family="table-cell")
    p = TableCellProperties(verticalalign="middle", padding="2mm",
                            wrapoption="wrap")
    if border:
        p.setAttribute("border", border)
    if btop:
        p.setAttribute("bordertop", btop)
    if bbot:
        p.setAttribute("borderbottom", bbot)
    st.addElement(p)
    doc.automaticstyles.addElement(st)
    return name


def _receipt_list(req) -> list[str]:
    """All receipt inputs: receipt_paths/receipts list or receipt_path string (;||newline)."""
    raw = getattr(req, "receipt_paths", None) or getattr(req, "receipts", None)
    if raw is None:
        raw = getattr(req, "receipt_path", None)
    if not raw:
        return []
    if isinstance(raw, (list, tuple)):
        return [str(p).strip() for p in raw if str(p).strip()]
    parts = [str(raw)]
    for sep in (";", "|", "\n"):
        parts = [s for p in parts for s in str(p).split(sep)]
    return [s.strip().strip(",") for s in (p.strip() for p in parts) if s.strip().strip(",")]


def _embed_receipts(path: str, shown: list[str]) -> None:
    """Zip-surgery: Pictures/receiptN.jpg + manifest entries (plain embed, no Pillow)."""
    import zipfile

    with zipfile.ZipFile(path, "r") as z:
        names = z.namelist()
        blobs = {n: z.read(n) for n in names}
    manifest = blobs["META-INF/manifest.xml"].decode("utf-8")
    for i, rp in enumerate(shown, 1):
        key = "Pictures/receipt%d.jpg" % i
        blobs[key] = Path(rp).read_bytes()
        mt = "image/png" if Path(rp).suffix.lower() == ".png" else "image/jpeg"
        entry = ('<manifest:file-entry manifest:full-path="%s" '
                 'manifest:media-type="%s"/>' % (key, mt))
        if key not in manifest:
            manifest = manifest.replace("</manifest:manifest>",
                                        " " + entry + "</manifest:manifest>")
    blobs["META-INF/manifest.xml"] = manifest.encode("utf-8")
    with zipfile.ZipFile(path, "w") as z:
        if "mimetype" in blobs:
            z.writestr("mimetype", blobs["mimetype"], compress_type=zipfile.ZIP_STORED)
        for n in names:
            if n == "mimetype":
                continue
            z.writestr(n, blobs[n], compress_type=zipfile.ZIP_DEFLATED)
        for i in range(1, len(shown) + 1):
            key = "Pictures/receipt%d.jpg" % i
            if key not in names:
                z.writestr(key, blobs[key], compress_type=zipfile.ZIP_DEFLATED)


def compose(title: str, doc_type: str, ctx: dict, pairs: list[tuple[str, str]],
            steps: list[tuple[str, str, str, str]], out: str,
            receipts: list[str] | None = None, receipt_total: int = 0) -> str:
    doc = OpenDocumentSpreadsheet()
    lay = PageLayout(name="atlas_hr_v3")
    lay.addElement(PageLayoutProperties(
        pagewidth="21cm", pageheight="29.7cm", printorientation="portrait",
        margintop="0.7cm", marginbottom="1cm", marginleft="1cm",
        marginright="1cm"))
    doc.automaticstyles.addElement(lay)
    mp = MasterPage(name="Default", pagelayoutname="atlas_hr_v3")
    ft = Footer()
    fp = P()
    fp.addText("Generated by Atlas-Bot | Page ")
    fp.addElement(PageNumber())
    fstyle = _ts(doc, "hrv3foot", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    fp.setAttribute("stylename", fstyle)
    ft.addElement(fp)
    mp.addElement(ft)
    doc.masterstyles.addElement(mp)
    tabst = Style(name="tab_hr_v3", family="table", masterpagename="Default")
    doc.automaticstyles.addElement(tabst)

    t_title = _ts(doc, "hrv3title", size="17pt", bold=True)
    t_meta = _ts(doc, "hrv3meta", size="10pt", bold=True)
    t_val = _ts(doc, "hrv3val")
    t_hdr = _ts(doc, "hrv3hdr", bold=True)
    t_foot = _ts(doc, "hrv3footc", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    c_plain = _cs(doc, "hrv3plain")
    c_cell = _cs(doc, "hrv3cell", border=D.V2_HAIRLINE)
    c_hdr = _cs(doc, "hrv3hdr", border=D.V2_HAIRLINE, bbot=D.V2_HDR_RULE)
    c_tot = _cs(doc, "hrv3tot", border=D.V2_HAIRLINE, btop=D.V2_HDR_RULE)
    hr = Style(name="hrv3headrow", family="table-row")
    hr.addElement(TableRowProperties(minrowheight="0.9cm"))
    doc.automaticstyles.addElement(hr)
    rr = Style(name="hrv3receiptrow", family="table-row")
    rr.addElement(TableRowProperties(rowheight="6.5cm",
                                     useoptimalrowheight="false"))
    doc.automaticstyles.addElement(rr)

    table = Table(name="HR", stylename="tab_hr_v3")
    for i, w in enumerate(WIDTHS):
        cs = Style(name="hrv3col%d" % i, family="table-column")
        cs.addElement(TableColumnProperties(columnwidth=w))
        doc.automaticstyles.addElement(cs)
        col = TableColumn()
        col.setAttribute("stylename", "hrv3col%d" % i)
        table.addElement(col)

    def mrow(text, tstyle, cstyle=c_plain):
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", cstyle)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", tstyle)
        p.addText(text)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)

    def drow(vals, cstyle, tstyle):
        r = TableRow()
        for v in vals:
            c = TableCell()
            c.setAttribute("stylename", cstyle)
            p = P()
            p.setAttribute("stylename", tstyle)
            p.addText(str(v))
            c.addElement(p)
            r.addElement(c)
        table.addElement(r)
        return r

    if LOGO_SRC.exists():
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", c_plain)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", fstyle)
        frame = Frame(name="Logo", width="3.2cm", height="1.1cm",
                      x="6.9cm", y="0.1cm", anchortype="paragraph")
        frame.addElement(Image(href="Pictures/atlas_logo.png", type="simple",
                               show="embed", actuate="onLoad"))
        p.addElement(frame)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)
    else:
        mrow("ATLAS-BOT", t_meta)
    mrow(title, t_title)
    for _label, _val in D.cover_rows(doc_type, ctx):
        mrow("%s: %s" % (_label, _val),
             t_val if _label == "Automated By" else t_meta)
    for label, val in pairs:  # form body, EN-only, centered
        mrow("%s: %s" % (label, val), t_val)
    for i, rp in enumerate(receipts or []):  # ≤2 photos, LO-safe: frame
        r = TableRow()  # is a direct cell child (P-wrapped frames are dropped)
        r.setAttribute("stylename", "hrv3receiptrow")
        c = TableCell()
        c.setAttribute("stylename", c_plain)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        frame = Frame(name="Receipt%d" % (i + 1), width="8cm", height="6cm",
                      x="5.5cm", y="0.1cm")  # ponytail: x centers 8cm on 19cm
        frame.setAttribute("zindex", "0")
        img = Image(href="Pictures/receipt%d.jpg" % (i + 1),
                    type="simple", show="embed", actuate="onLoad")
        img.addElement(P())
        frame.addElement(img)
        c.addElement(frame)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)
    if receipt_total > len(receipts or []):
        mrow("%d attachments on file (2 shown)" % receipt_total, t_val)
    drow(["Step", "Decision", "Name", "Date"], c_hdr, t_hdr).setAttribute(
        "stylename", "hrv3headrow")
    for s in steps:  # zebra-free: summary-style hairline + top rule
        drow(list(s), c_tot, t_val)
    mrow("Generated by Atlas-Bot | %s" % ctx.get("reference", ""), t_foot)

    nrows = len(table.getElementsByType(TableRow))
    table.setAttribute("printranges", "A1:D%d" % nrows)
    doc.spreadsheet.addElement(table)
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    doc.save(out)
    if LOGO_SRC.exists():
        from scripts.build_hr_templates import _embed_logo
        _embed_logo(out)
    if receipts:
        _embed_receipts(out, receipts)
    return out


def _steps_of(req) -> list[tuple[str, str, str, str]]:
    def sig(role: str) -> tuple[str, str, str]:
        for s in req.signatures or []:
            if s.get("role") == role:
                return (str(s.get("decision", "") or "-"),
                        str(s.get("name", "") or "-"),
                        str(s.get("at", "") or "")[:10] or "-")
        return ("-", "-", "-")
    pm = sig("project_manager")
    hr = sig("hr")
    return [("1. PM Confirm", *pm), ("2. HR Decision", *hr)]


def build_advance(req, company: str = "", out: str = "") -> str:
    ctx = {"reference": "HR-%04d" % (req.id or 0),
           "date": req.created_at[:10] if getattr(req, "created_at", "") else "",
           "requester": req.requester_name or "",
           "chat-id": mask_chat(req.requester_chat_id),
           "site": req.site_id or "", "company": company or "",
           "automated-by": "Atlas-bot"}
    pairs = [("Amount", "%g" % req.amount), ("Reason", req.reason or "-"),
             ("Deduction Month", req.deduction_month or "-"),
             ("Note", req.note or "-")]
    return compose("Salary Advance Request", "advance", ctx, pairs,
                   _steps_of(req), out)


def build_transport(req, company: str = "", out: str = "") -> str:
    ctx = {"reference": "HR-%04d" % (req.id or 0),
           "date": req.created_at[:10] if getattr(req, "created_at", "") else "",
           "requester": req.requester_name or "",
           "chat-id": mask_chat(req.requester_chat_id),
           "site": req.site_id or "", "company": company or "",
           "automated-by": "Atlas-bot"}
    pairs = [("Amount", "%g" % req.amount), ("Reason", req.reason or "-"),
             ("Trip Date", req.trip_date or "-"),
             ("Report Ref", req.report_ref or "-"),
             ("Receipt", req.receipt_path or "attached" if getattr(
                 req, "receipt_path", "") else "-"),
             ("Note", req.note or "-")]
    all_r = _receipt_list(req)
    shown = [p for p in all_r if Path(p).exists()][:2]  # ponytail: bytes only
    return compose("Transport Allowance Request", "transport", ctx, pairs,
                   _steps_of(req), out, receipts=shown, receipt_total=len(all_r))
