"""No-labor v3 composer (empty-state, live path).

Converged onto the v3 cover+table system: cover via design.cover_rows
("daily": company/site/date/automated-by), intentional balanced empty body
(single bordered message row, no grid), portrait A4, single print-range +
footer. Business outcomes unchanged (zero-entry stays NO_REPORT).
"""

from __future__ import annotations

from pathlib import Path

from odf.draw import Frame, Image
from odf.opendocument import OpenDocumentSpreadsheet
from odf.style import (
    Footer, MasterPage, PageLayout, PageLayoutProperties,
    ParagraphProperties, Style, TableCellProperties,
    TableColumnProperties, TableRowProperties, TextProperties,
)
from odf.table import Table, TableCell, TableColumn, TableRow
from odf.text import P, PageNumber

from app.libre import design as D
from app.libre.daily_v3 import resolve_company

_ROOT = Path(__file__).parent.parent.parent.resolve()
LOGO_SRC = _ROOT / "assets" / "atlas_logo.png"
NCOLS = 8
WIDTHS = D.DAILY_V2_WIDTHS
EMPTY_BODY = "No labor entries were recorded for this reporting period."


def _ts(doc, name, size="10.5pt", bold=False, color=None, align="center"):
    st = Style(name=name, family="text")
    tp = TextProperties(fontfamily=D.FONTS, fontsize=size)
    if bold:
        tp.setAttribute("fontweight", "bold")
    if color:
        tp.setAttribute("color", color)
    st.addElement(tp)
    st.addElement(ParagraphProperties(textalign=align))
    doc.styles.addElement(st)
    return name


def _cs(doc, name, border=None, btop=None, bbot=None):
    st = Style(name=name, family="table-cell")
    p = TableCellProperties(verticalalign="middle", padding="2mm",
                            wrapoption="wrap")
    if border:
        p.setAttribute("border", border)
    if btop:
        p.setAttribute("bordertop", btop)
    if bbot:
        p.setAttribute("borderbottom", bbot)
    st.addElement(p)
    doc.automaticstyles.addElement(st)
    return name


def compose(ctx: dict, out: str) -> str:
    doc = OpenDocumentSpreadsheet()
    lay = PageLayout(name="atlas_nolabor_v3")
    lay.addElement(PageLayoutProperties(
        pagewidth="21cm", pageheight="29.7cm", printorientation="portrait",
        margintop="0.7cm", marginbottom="1cm", marginleft="1cm",
        marginright="1cm"))
    doc.automaticstyles.addElement(lay)
    mp = MasterPage(name="Default", pagelayoutname="atlas_nolabor_v3")
    ft = Footer()
    fp = P()
    fp.addText("Generated by Atlas-Bot | Page ")
    fp.addElement(PageNumber())
    fstyle = _ts(doc, "nlv3foot", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    fp.setAttribute("stylename", fstyle)
    ft.addElement(fp)
    mp.addElement(ft)
    doc.masterstyles.addElement(mp)
    tabst = Style(name="tab_nlv3", family="table", masterpagename="Default")
    doc.automaticstyles.addElement(tabst)

    t_title = _ts(doc, "nlv3title", size="17pt", bold=True)
    t_meta = _ts(doc, "nlv3meta", size="10pt", bold=True)
    t_val = _ts(doc, "nlv3val")
    t_foot = _ts(doc, "nlv3footc", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    c_plain = _cs(doc, "nlv3plain")
    c_body = _cs(doc, "nlv3body", border=D.V2_HAIRLINE)

    table = Table(name="NoLabor", stylename="tab_nlv3")
    for i, w in enumerate(WIDTHS):
        cs = Style(name="nlv3col%d" % i, family="table-column")
        cs.addElement(TableColumnProperties(columnwidth=w))
        doc.automaticstyles.addElement(cs)
        col = TableColumn()
        col.setAttribute("stylename", "nlv3col%d" % i)
        table.addElement(col)

    def mrow(text, tstyle, cstyle=c_plain):
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", cstyle)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", tstyle)
        p.addText(text)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)

    if LOGO_SRC.exists():
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", c_plain)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", fstyle)
        frame = Frame(name="Logo", width="3.2cm", height="1.1cm",
                      x="7.9cm", y="0.1cm", anchortype="paragraph")
        frame.addElement(Image(href="Pictures/atlas_logo.png", type="simple",
                               show="embed", actuate="onLoad"))
        p.addElement(frame)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)
    else:
        mrow("ATLAS-BOT", t_meta)
    mrow("No Labor Report", t_title)
    for _label, _val in D.cover_rows("daily", ctx):
        mrow("%s: %s" % (_label, _val),
             t_val if _label == "Automated By" else t_meta)
    mrow(EMPTY_BODY, t_val, c_body)
    mrow("Generated by Atlas-Bot | %s" % ctx.get("date", ""), t_foot)

    nrows = len(table.getElementsByType(TableRow))
    table.setAttribute("printranges", "A1:H%d" % nrows)
    doc.spreadsheet.addElement(table)
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    doc.save(out)
    if LOGO_SRC.exists():
        from scripts.build_hr_templates import _embed_logo
        _embed_logo(out)
    return out


def build(report, config=None, output_path: str | None = None) -> str:
    if output_path is None:
        output_path = str(config.docs_folder_path / f"{report.date}.ods") \
            if config is not None else f"{report.date}.ods"
    ctx = {"company": resolve_company(config),
           "site": getattr(report, "site_id", "") or "",
           "date": report.date}
    return compose(ctx, output_path)
