"""Build Daily v3 NEW LOOK: cover + data table composed in ONE sheet.

Cover (top, all white/centered, portrait A4): title + Automated By
Atlas-bot + Company (config.yaml `company` key, else OPAL fixture) +
Site + Date + logo row (assets/atlas_logo.png, text wordmark if absent).
Table below: white, centered h+v, wrap on, 2mm padding, 100% printable
widths, 0.5pt #D0D0D0 hairline, bold header + bottom rule, bold totals +
top rule. Single print-range, single footer. Daily only; v1/v2 intact.

Usage: python scripts/build_daily_v3.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_root = Path(__file__).parent.parent.resolve()
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from odf.draw import Frame, Image  # noqa: E402
from odf.opendocument import OpenDocumentSpreadsheet  # noqa: E402
from odf.style import (  # noqa: E402
    Footer,
    MasterPage,
    PageLayout,
    PageLayoutProperties,
    ParagraphProperties,
    Style,
    TableCellProperties,
    TableColumnProperties,
    TableRowProperties,
    TextProperties,
)
from odf.table import Table, TableCell, TableColumn, TableRow  # noqa: E402
from odf.text import P, PageNumber  # noqa: E402

from app.libre import design as D  # noqa: E402
from scripts.build_hr_templates import _embed_logo  # noqa: E402

NCOLS = 8
LOGO_SRC = _root / "assets" / "atlas_logo.png"
WIDTHS = D.DAILY_V2_WIDTHS  # 8 cols, sums to 19cm portrait printable
HEADERS = ["#", "Contractor", "Type", "Zone", "Workers", "Craftsmen",
           "Helpers", "Details"]
FIXTURE = {"company": "OPAL Construction Co.", "site": "15 - NASH",
           "date": "17/09/2026"}
ROWS = [
    ("Al-Noor Builders", "Civil", "Zone A", 12, 8, 4, "8 Mason, 4 Helper"),
    ("Skyline Electrics", "Electrical", "Zone B", 7, 5, 2, "5 Electrician, 2 Helper"),
    ("Delta Formwork", "Carpentry", "Zone A", 9, 6, 3, "6 Carpenter, 3 Helper"),
    ("Palm Steel Works", "Steel", "Zone C", 11, 7, 4, "7 Steel fixer, 4 Helper"),
    ("Nile Finishing", "Finishing", "Zone B", 5, 3, 2, "3 Painter, 2 Helper"),
]


def _company() -> str:
    m = re.search(r"^company:\s*[\"']?(.+?)[\"']?\s*$",
                  (_root / "config" / "config.yaml").read_text(encoding="utf-8"),
                  re.M)
    return m.group(1).strip() if m else FIXTURE["company"]


def _ts(doc, name, size="10.5pt", bold=False, color=None, align="center"):
    st = Style(name=name, family="text")
    tp = TextProperties(fontfamily=D.FONTS, fontsize=size)
    if bold:
        tp.setAttribute("fontweight", "bold")
    if color:
        tp.setAttribute("color", color)
    st.addElement(tp)
    pp = ParagraphProperties(textalign=align)
    st.addElement(pp)
    doc.styles.addElement(st)
    return name


def _cs(doc, name, border=None, btop=None, bbot=None):
    st = Style(name=name, family="table-cell")
    p = TableCellProperties(verticalalign="middle", padding="2mm")
    if border:
        p.setAttribute("border", border)
    if btop:
        p.setAttribute("bordertop", btop)
    if bbot:
        p.setAttribute("borderbottom", bbot)
    st.addElement(p)
    doc.automaticstyles.addElement(st)
    return name


def build() -> str:
    from app.libre.daily_v3 import compose  # single source for live path

    ctx = {"company": _company(), "site": FIXTURE["site"],
           "date": FIXTURE["date"]}
    rows = [(co, ty, zo, w, cr, he, de) for co, ty, zo, w, cr, he, de in ROWS]
    return compose(ctx, rows, str(_root / "exports" / "review" / "daily_v3.ods"))


def _legacy_build() -> str:
    ctx = {"company": _company(), "site": FIXTURE["site"],
           "date": FIXTURE["date"]}
    doc = OpenDocumentSpreadsheet()
    lay = PageLayout(name="atlas_v3")
    lay.addElement(PageLayoutProperties(
        pagewidth="21cm", pageheight="29.7cm", printorientation="portrait",
        margintop="0.7cm", marginbottom="1cm", marginleft="1cm",
        marginright="1cm"))
    doc.automaticstyles.addElement(lay)
    mp = MasterPage(name="Default", pagelayoutname="atlas_v3")
    ft = Footer()
    fp = P()
    fp.addText("Generated by Atlas-Bot | Page ")
    fp.addElement(PageNumber())
    fstyle = _ts(doc, "v3foot", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    fp.setAttribute("stylename", fstyle)
    ft.addElement(fp)
    mp.addElement(ft)
    doc.masterstyles.addElement(mp)
    tabst = Style(name="tab_v3", family="table", masterpagename="Default")
    doc.automaticstyles.addElement(tabst)

    t_title = _ts(doc, "v3title", size="17pt", bold=True)
    t_meta = _ts(doc, "v3meta", size="10pt", bold=True)
    t_val = _ts(doc, "v3val")
    t_hdr = _ts(doc, "v3hdr", bold=True)
    t_foot = _ts(doc, "v3footc", size=D.FOOT_SIZE, color=D.FOOT_GRAY)
    c_plain = _cs(doc, "v3plain")
    c_cell = _cs(doc, "v3cell", border=D.V2_HAIRLINE)
    c_hdr = _cs(doc, "v3hdr", border=D.V2_HAIRLINE, bbot=D.V2_HDR_RULE)
    c_tot = _cs(doc, "v3tot", border=D.V2_HAIRLINE, btop=D.V2_HDR_RULE)
    hr = Style(name="v3headrow", family="table-row")
    hr.addElement(TableRowProperties(minrowheight="0.9cm"))
    doc.automaticstyles.addElement(hr)

    table = Table(name="Daily", stylename="tab_v3")
    for i, w in enumerate(WIDTHS):
        cs = Style(name="v3col%d" % i, family="table-column")
        cs.addElement(TableColumnProperties(columnwidth=w))
        doc.automaticstyles.addElement(cs)
        col = TableColumn()
        col.setAttribute("stylename", "v3col%d" % i)
        table.addElement(col)

    def mrow(text, tstyle, cstyle=c_plain):  # merged cover/table-full row
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", cstyle)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", tstyle)
        p.addText(text)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)

    def drow(vals, cstyle, tstyle):  # 8-col data row
        r = TableRow()
        for v in vals:
            c = TableCell()
            c.setAttribute("stylename", cstyle)
            p = P()
            p.setAttribute("stylename", tstyle)
            p.addText(str(v))
            c.addElement(p)
            r.addElement(c)
        table.addElement(r)
        return r

    if LOGO_SRC.exists():  # logo row; else text wordmark only
        r = TableRow()
        c = TableCell()
        c.setAttribute("stylename", c_plain)
        c.setAttribute("numbercolumnsspanned", str(NCOLS))
        p = P()
        p.setAttribute("stylename", fstyle)
        frame = Frame(name="Logo", width="3.2cm", height="1.1cm",
                      x="7.9cm", y="0.1cm", anchortype="paragraph")
        frame.addElement(Image(href="Pictures/atlas_logo.png", type="simple",
                               show="embed", actuate="onLoad"))
        p.addElement(frame)
        c.addElement(p)
        r.addElement(c)
        for _ in range(NCOLS - 1):
            r.addElement(TableCell())
        table.addElement(r)
    else:
        mrow("ATLAS-BOT", t_meta)
    mrow("Daily Labor Report", t_title)
    for _label, _val in D.cover_rows("daily", ctx):
        mrow("%s: %s" % (_label, _val),
             t_val if _label == "Automated By" else t_meta)
    drow(list(HEADERS), c_hdr, t_hdr).setAttribute("stylename", "v3headrow")
    tw = tc = th = 0
    for n, (co, ty, zo, w, cr, he, de) in enumerate(ROWS, 1):
        drow([n, co, ty, zo, w, cr, he, de], c_cell, t_val)
        tw += w
        tc += cr
        th += he
    drow(["", "Total", "", "", tw, tc, th, ""], c_tot, t_hdr)
    # Provenance content row (headless LO drops master footers: v2 same).
    mrow("Generated by Atlas-Bot | %s" % FIXTURE["date"], t_foot)

    nrows = len(table.getElementsByType(TableRow))
    table.setAttribute("printranges", "A1:H%d" % nrows)
    doc.spreadsheet.addElement(table)
    out = str(_root / "exports" / "review" / "daily_v3.ods")
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    doc.save(out)
    if LOGO_SRC.exists():
        _embed_logo(out)
    return out


if __name__ == "__main__":
    ods = build()
    print("ods:", ods, "| logo:", "y" if LOGO_SRC.exists() else "n")
    from app.models.config import AppConfig
    from app.libre.pdf import PDFGenerator

    pdf = PDFGenerator(AppConfig()).convert_to_pdf(
        ods, str(_root / "exports" / "review" / "daily_v3.pdf"))
    print("pdf:", pdf)
