"""Author HR .ots templates (advance + transport, EN LTR + AR RTL).

Reproducible + fork-customizable: PALETTE/FONTS/LABELS below, rerun.
Value cells carry [MARKERS] replaced by the fill engine (language
independent). AR variants mirror cell order for true RTL layout.

Visual system:
  fonts: Arial, Liberation Sans, DejaVu Sans, sans-serif (all scripts)
  title 18pt bold white on navy / bands 13pt / labels 10pt bold /
  values 11pt / footer 8.5pt gray / gold rule under title
  logo: assets/atlas_logo.png embedded top corner (EN left, AR right)

Usage:
    python scripts/build_hr_templates.py
"""

from __future__ import annotations

import shutil
import tempfile
import zipfile
from pathlib import Path

from odf.draw import Frame, Image
from odf.opendocument import OpenDocumentSpreadsheet
from odf.style import (
    ParagraphProperties,
    Style,
    TableCellProperties,
    TableColumnProperties,
    TextProperties,
)
from odf.table import Table, TableCell, TableColumn, TableRow
from odf.text import P

NAVY = "#1b3a5f"
GOLD = "#c5a04a"
LIGHT = "#eaf0f7"
GRAY = "#6b7280"
GRID = "#9aa5b1"
FONTS = "Arial, Liberation Sans, DejaVu Sans, sans-serif"
LOGO_SRC = Path("assets/atlas_logo.png")
LOGO_W, LOGO_H = "3.2cm", "1.1cm"

LABELS = {
    "en": {
        "adv_title": "Salary Advance Request",
        "tr_title": "Transport Allowance Request",
        "ref": "Ref", "date": "Date", "site": "Site",
        "requester": "Requester", "chat": "Chat ID",
        "amount": "Amount", "reason": "Reason",
        "trip_date": "Trip Date", "report_ref": "Report Ref",
        "receipt": "Receipt", "ded_month": "Deduction Month",
        "routing": "Approval Routing - sign and date in sequence",
        "pm_step": "1. PM Confirm", "hr_step": "2. HR Decision",
        "name": "Name", "decision": "Decision",
        "note": "Note", "footer": "Generated by Atlas-Bot - keep with payroll records",
    },
    "ar": {
        "adv_title": "طلب سلفة",
        "tr_title": "طلب بدل مواصلات",
        "ref": "الرقم", "date": "التاريخ", "site": "الموقع",
        "requester": "مقدم الطلب", "chat": "رقم الشات",
        "amount": "المبلغ", "reason": "السبب",
        "trip_date": "تاريخ الرحلة", "report_ref": "مرجع التقرير",
        "receipt": "الإيصال", "ded_month": "شهر الخصم",
        "routing": "مسار الاعتماد - وقع وارخ بالترتيب",
        "pm_step": "1. اعتماد مدير المشروع", "hr_step": "2. قرار الموارد البشرية",
        "name": "الاسم", "decision": "القرار",
        "note": "ملاحظة", "footer": "تم الإنشاء بواسطة Atlas-Bot - يحفظ مع records الرواتب",
    },
}


def _text_style(doc, name: str, size="11pt", bold=False, color=None, align=None) -> str:
    st = Style(name=name, family="text")
    tp = TextProperties(fontfamily=FONTS, fontsize=size)
    if bold:
        tp.setAttribute("fontweight", "bold")
    if color:
        tp.setAttribute("color", color)
    st.addElement(tp)
    if align:
        st.addElement(ParagraphProperties(textalign=align))
    doc.styles.addElement(st)
    return name


def _cell_style(doc, name: str, bg=None, border=True) -> str:
    st = Style(name=name, family="table-cell")
    props = {}
    if bg:
        props["backgroundcolor"] = bg
    if border:
        props["border"] = "0.5pt solid %s" % GRID
        props["padding"] = "1.8mm"
    if props:
        st.addElement(TableCellProperties(**props))
    doc.automaticstyles.addElement(st)
    return name


def _para(text: str, style: str) -> P:
    p = P()
    p.setAttribute("stylename", style)
    p.addText(text)
    return p


def _cell(text: str, cell_style: str, text_style: str, span: int = 1) -> TableCell:
    cell = TableCell()
    cell.setAttribute("stylename", cell_style)
    if span and span > 1:
        cell.setAttribute("numbercolumnsspanned", str(span))
    cell.addElement(_para(text, text_style))
    return cell


def _gold_rule_cell(cell_style: str) -> TableCell:
    cell = TableCell()
    cell.setAttribute("stylename", cell_style)
    p = P()
    p.addText("─" * 72)
    cell.addElement(p)
    return cell


def build(kind: str, lang: str) -> str:
    """Author one template file. Returns output path."""
    labels = LABELS[lang]
    rtl = lang == "ar"
    title = labels["adv_title"] if kind == "advance" else labels["tr_title"]
    suffix = "" if lang == "en" else "_ar"
    name = "hr-advance" if kind == "advance" else "acc-transport"
    out = "templates/%s-template%s.ots" % (name, suffix)

    doc = OpenDocumentSpreadsheet()

    # text styles
    t_title = _text_style(doc, "t_%s_title" % lang, size="18pt", bold=True, color="#ffffff", align="center")
    t_band = _text_style(doc, "t_%s_band" % lang, size="13pt", bold=True, color="#ffffff", align="center")
    t_label = _text_style(doc, "t_%s_label" % lang, size="10pt", bold=True)
    t_value = _text_style(doc, "t_%s_value" % lang, size="11pt")
    t_note = _text_style(doc, "t_%s_note" % lang, size="8.5pt", color=GRAY, align="center")
    t_gold = _text_style(doc, "t_%s_gold" % lang, size="8pt", color=GOLD, align="center")

    # cell styles
    c_title = _cell_style(doc, "c_%s_title" % lang, bg=NAVY, border=False)
    c_band = _cell_style(doc, "c_%s_band" % lang, bg=NAVY, border=False)
    c_label = _cell_style(doc, "c_%s_label" % lang, bg=LIGHT)
    c_value = _cell_style(doc, "c_%s_value" % lang)
    c_note = _cell_style(doc, "c_%s_note" % lang, border=False)
    c_gold = _cell_style(doc, "c_%s_gold" % lang, border=False)
    c_plain = _cell_style(doc, "c_%s_plain" % lang, border=False)

    table = Table(name="Form")
    for width in ("3.6cm", "6.2cm", "3.6cm", "6.2cm"):
        col = TableColumn()
        col_style = Style(name="col_%s_%s" % (lang, width.replace(".", "_")), family="table-column")
        col_style.addElement(TableColumnProperties(columnwidth=width))
        doc.automaticstyles.addElement(col_style)
        col.setAttribute("stylename", col_style.getAttribute("name"))
        table.addElement(col)

    def row(cells: list) -> TableRow:
        """cells = [(text, cell_style, text_style, span)]. Mirrored for RTL."""
        ordered = list(reversed(cells)) if rtl else list(cells)
        row_el = TableRow()
        used = 0
        for text, cstyle, tstyle, span in ordered:
            row_el.addElement(_cell(text, cstyle, tstyle, span))
            used += span or 1
        while used < 4:
            row_el.addElement(TableCell())
            used += 1
        return row_el

    L, V = c_label, c_value  # noqa: E741

    # header: logo + title
    logo_cell = TableCell()
    logo_cell.setAttribute("stylename", c_plain)
    logo_p = P()
    logo_p.setAttribute("stylename", t_note)
    frame = Frame(name="Logo", width=LOGO_W, height=LOGO_H, x="0cm", y="0cm")
    frame.addElement(Image(href="Pictures/atlas_logo.png"))
    logo_p.addElement(frame)
    logo_cell.addElement(logo_p)

    header = TableRow()
    title_cell = _cell(title, c_title, t_title, 3)
    if rtl:
        header.addElement(title_cell)
        header.addElement(logo_cell)
    else:
        header.addElement(logo_cell)
        header.addElement(title_cell)
    table.addElement(header)

    table.addElement(row([
        ("%s: [REF]" % labels["ref"], L, t_label, 1),
        ("", V, t_value, 1),
        ("%s: [DATE]" % labels["date"], L, t_label, 1),
        ("%s: [SITE]" % labels["site"], L, t_label, 1),
    ]))
    table.addElement(row([
        ("%s: [REQUESTER]" % labels["requester"], L, t_label, 1),
        ("", V, t_value, 1),
        ("%s: [CHAT_ID]" % labels["chat"], L, t_label, 1),
        ("", V, t_value, 1),
    ]))
    table.addElement(row([
        ("%s: [AMOUNT]" % labels["amount"], L, t_label, 1),
        ("", V, t_value, 1),
        ("%s: [REASON]" % labels["reason"], L, t_label, 1),
        ("", V, t_value, 1),
    ]))
    if kind == "transport":
        table.addElement(row([
            ("%s: [TRIP_DATE]" % labels["trip_date"], L, t_label, 1),
            ("", V, t_value, 1),
            ("%s: [REPORT_REF]" % labels["report_ref"], L, t_label, 1),
            ("", V, t_value, 1),
        ]))
        table.addElement(row([
            (labels["receipt"] + ":", L, t_label, 1),
            ("[RECEIPT]", V, t_value, 3),
        ]))
    else:
        table.addElement(row([
            ("%s: [DED_MONTH]" % labels["ded_month"], L, t_label, 1),
            ("", V, t_value, 3),
        ]))
    table.addElement(row([(labels["routing"], c_band, t_band, 4)]))
    table.addElement(row([
        ("%s: [PM_DECISION]" % labels["pm_step"], L, t_label, 1),
        ("%s: [PM_NAME]" % labels["name"], V, t_value, 1),
        ("%s: [PM_DATE]" % labels["date"], L, t_label, 1),
        ("", V, t_value, 1),
    ]))
    table.addElement(row([
        ("%s: [HR_DECISION]" % labels["hr_step"], L, t_label, 1),
        ("%s: [HR_NAME]" % labels["name"], V, t_value, 1),
        ("%s: [HR_DATE]" % labels["date"], V, t_value, 1),
        ("", V, t_value, 1),
    ]))
    table.addElement(row([
        ("%s: [NOTE]" % labels["note"], L, t_label, 1),
        ("", V, t_value, 3),
    ]))
    gold_row = TableRow()
    gold_row.addElement(_gold_rule_cell(c_gold))
    for _ in range(3):
        gold_row.addElement(TableCell())
    table.addElement(gold_row)
    table.addElement(row([(labels["footer"], c_note, t_note, 4)]))

    doc.spreadsheet.addElement(table)
    doc.save(out)

    # embed logo bytes + manifest entry
    _embed_logo(out)
    return out


def _embed_logo(path: str) -> None:
    """Zip-surgery: Pictures/atlas_logo.png + manifest entry."""
    import re

    with zipfile.ZipFile(path, "r") as z:
        names = z.namelist()
        blobs = {n: z.read(n) for n in names}
    with open(str(LOGO_SRC), "rb") as f:
        blobs["Pictures/atlas_logo.png"] = f.read()
    manifest = blobs["META-INF/manifest.xml"].decode("utf-8")
    entry = ('<manifest:file-entry manifest:full-path="Pictures/atlas_logo.png" '
             'manifest:media-type="image/png"/>')
    if "Pictures/atlas_logo.png" not in manifest:
        manifest = manifest.replace("</manifest:manifest>",
                                    " " + entry + "</manifest:manifest>")
    blobs["META-INF/manifest.xml"] = manifest.encode("utf-8")
    with zipfile.ZipFile(path, "w") as z:
        if "mimetype" in blobs:
            z.writestr("mimetype", blobs["mimetype"], compress_type=zipfile.ZIP_STORED)
        for n in names:
            if n == "mimetype":
                continue
            z.writestr(n, blobs[n], compress_type=zipfile.ZIP_DEFLATED)
        if "Pictures/atlas_logo.png" not in names:
            z.writestr("Pictures/atlas_logo.png", blobs["Pictures/atlas_logo.png"],
                       compress_type=zipfile.ZIP_DEFLATED)
    # validate round-trip
    from odf.opendocument import load as _load

    _load(path)


if __name__ == "__main__":
    for _kind in ("advance", "transport"):
        for _lang in ("en", "ar"):
            print("built:", build(_kind, _lang))
